# Generated by Django 4.1.5 on 2023-01-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Местонахождение учебных заведений',
                'verbose_name_plural': 'Местонахождения учебных заведений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversitySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Предмет учебного заведения',
                'verbose_name_plural': 'Предметы учебных заведений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMilitary', models.BooleanField(db_index=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип учебного заведения',
                'verbose_name_plural': 'Типы учебных заведений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя учебного заведения')),
                ('summary', models.TextField(verbose_name='Краткая информация')),
                ('avg_price', models.IntegerField(blank=True, null=True, verbose_name='Средняя стоимость обучения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('avg_score', models.IntegerField(blank=True, null=True, verbose_name='Средние баллы для поступления')),
                ('text_history', models.TextField(blank=True, null=True, verbose_name='История')),
                ('paragraph1', models.TextField(blank=True, null=True, verbose_name='Информация [1 параграф]')),
                ('paragraph2', models.TextField(blank=True, null=True, verbose_name='Информация [2 параграф]')),
                ('paragraph3', models.TextField(blank=True, null=True, verbose_name='Информация [3 параграф]')),
                ('paragraph4', models.TextField(blank=True, null=True, verbose_name='Информация [4 параграф]')),
                ('paragraph5', models.TextField(blank=True, null=True, verbose_name='Информация [5 параграф]')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон учебного заведения')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб сайт учебного заведения')),
                ('img1', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение учебного заведения')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_after9', models.BooleanField(blank=True, null=True, verbose_name='После 9 класса?')),
                ('is_after11', models.BooleanField(blank=True, null=True, verbose_name='После 11 класса?')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universitygo.universitylocation', verbose_name='Место нахождения')),
                ('subject1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject1', to='universitygo.universitysubject', verbose_name='Предмет1')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject2', to='universitygo.universitysubject', verbose_name='Предмет2')),
                ('subject3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject3', to='universitygo.universitysubject', verbose_name='Предмет3')),
                ('subject4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject4', to='universitygo.universitysubject', verbose_name='Предмет4')),
                ('subject5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject5', to='universitygo.universitysubject', verbose_name='Предмет5')),
                ('unv_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universitygo.universitytype', verbose_name='Тип учебного заведения [Гражданский - False/Военный - True]')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
                'ordering': ['id'],
            },
        ),
    ]
