# Generated by Django 4.1.5 on 2023-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitygo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='after',
            field=models.IntegerField(blank=True, null=True, verbose_name='После какого класса'),
        ),
        migrations.AlterField(
            model_name='university',
            name='img1',
            field=models.ImageField(upload_to='photos', verbose_name='Изображение учебного заведения'),
        ),
    ]
